package models

type Player struct {
	ID                            int     `json:"id"`
	FirstName                     string  `json:"first_name"`
	SecondName                    string  `json:"second_name"`
	WebName                       string  `json:"web_name"`
	News                          string  `json:"news"`
	Team                          int     `json:"team"`
	ElementType                   int     `json:"element_type"`
	NowCost                       int     `json:"now_cost"`
	SelectedByPercent             string  `json:"selected_by_percent"`
	TotalPoints                   int     `json:"total_points"`
	Minutes                       int     `json:"minutes"`
	GoalsScored                   int     `json:"goals_scored"`
	Assists                       int     `json:"assists"`
	CleanSheets                   int     `json:"clean_sheets"`
	GoalsConceded                 int     `json:"goals_conceded"`
	OwnGoals                      int     `json:"own_goals"`
	PenaltiesSaved                int     `json:"penalties_saved"`
	PenaltiesMissed               int     `json:"penalties_missed"`
	YellowCards                   int     `json:"yellow_cards"`
	RedCards                      int     `json:"red_cards"`
	Saves                         int     `json:"saves"`
	Bonus                         int     `json:"bonus"`
	Bps                           int     `json:"bps"`
	Influence                     string  `json:"influence"`
	Creativity                    string  `json:"creativity"`
	Threat                        string  `json:"threat"`
	IctIndex                      string  `json:"ict_index"`
	ExpectedGoals                 string  `json:"expected_goals"`
	ExpectedAssists               string  `json:"expected_assists"`
	ExpectedGoalInvolvements      string  `json:"expected_goal_involvements"`
	ExpectedGoalsConceded         string  `json:"expected_goals_conceded"`
	ExpectedGoalsPer90            float64 `json:"expected_goals_per_90"`
	SavesPer90                    float64 `json:"saves_per_90"`
	ExpectedAssistsPer90          float64 `json:"expected_assists_per_90"`
	ExpectedGoalInvolvementsPer90 float64 `json:"expected_goal_involvements_per_90"`
	ExpectedGoalsConcededPer90    float64 `json:"expected_goals_conceded_per_90"`
	GoalsConcededPer90            float64 `json:"goals_conceded_per_90"`
	NowCostRank                   int     `json:"now_cost_rank"`
	NowCostRankType               int     `json:"now_cost_rank_type"`
	Form                          string  `json:"form"`
	FormRank                      int     `json:"form_rank"`
	FormRankType                  int     `json:"form_rank_type"`
	PointsPerGameRank             int     `json:"points_per_game_rank"`
	PointsPerGameRankType         int     `json:"points_per_game_rank_type"`
	SelectedRank                  int     `json:"selected_rank"`
	SelectedRankType              int     `json:"selected_rank_type"`
	StartsPer90                   float64 `json:"starts_per_90"`
	CleanSheetsPer90              float64 `json:"clean_sheets_per_90"`
}
